<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	  <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
	  <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Asterism</RootNamespace>
    <AssemblyName>AsterismCore</AssemblyName>
    <LangVersion>12.0</LangVersion>
    <StartupObject />
    <AssemblyTitle>CoreCommon</AssemblyTitle>
    <Company>molmolgames</Company>
    <Product>CoreCommon</Product>
    <Copyright>Copyright ©  2024</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <NeutralLanguage>ja-JP</NeutralLanguage>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <AnalysisLevel>latest</AnalysisLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <UseWinFormsOutOfProcDesigner>True</UseWinFormsOutOfProcDesigner>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>none</DebugType>
    <OutputPath>..\..\Unity\Asterism Engine\Assets\asterism\Plugins\x86_64\</OutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UseWinFormsOutOfProcDesigner>True</UseWinFormsOutOfProcDesigner>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Properties\**" />
    <Compile Remove="UnitTest\**" />
    <EmbeddedResource Remove="Properties\**" />
    <EmbeddedResource Remove="UnitTest\**" />
    <None Remove="Properties\**" />
    <None Remove="UnitTest\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.12.2" />
    <Reference Update="System.Drawing">
      <HintPath>..\..\..\..\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\System.Drawing.dll</HintPath>
    </Reference>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.6.0-preview3.19128.7" />
  </ItemGroup>
</Project>