<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	  <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
	  <TargetFramework>net9.0</TargetFramework>
    <OutputType>Library</OutputType>
    <LangVersion>12.0</LangVersion>
    <AssemblyTitle>UnitTest</AssemblyTitle>
    <Product>UnitTest</Product>
    <Copyright>Copyright ©  2024</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Properties\**" />
    <EmbeddedResource Remove="Properties\**" />
    <None Remove="Properties\**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Common\Crypt\AESTest.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="System\CronTest.cs" />
    <Compile Include="System\PomodoroTest.cs" />
    <Compile Include="System\ReminderTest.cs" />
    <Compile Include="System\DomAnalysis\DomParserTest.cs" />
    <Compile Include="System\DomAnalysis\DomElementTest.cs" />
    <Compile Include="System\DomAnalysis\StructureAnalyzerTest.cs" />
    <Compile Include="System\DomAnalysis\ParsingConfigTest.cs" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.0.0-preview.25454.2" />
    <PackageReference Include="MSTest.TestFramework" Version="4.0.0-preview.25454.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="System.Reactive" Version="6.0.2" />
    <PackageReference Include="System.Reactive.Core" Version="6.0.2" />
    <PackageReference Include="System.Reactive.Linq" Version="6.0.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Common.csproj" />
  </ItemGroup>
</Project>